### PR TITLE
 Added an effect which usses particle system.

### PR DESCRIPTION
**Pull request by distroinfinity**
Created an effect which uses particle system as addressed in issue #12  in the 'Projects/Particle-System/Butterflies' directory.

### CODE REVIEW

**Review by lopeselio — CHANGES_REQUESTED** [review]
Hey @distroinfinity this is a great use of emitters in your project. Just need a couple of fixes.
- [] You have imported the audio. But it doesn't seem to play in the background. Check your patch editor. 
- [] ` Projects/Particle-System/Butterflies/textures/1(2).png` and `Projects/Particle-System/Butterflies/textures/2(4).png` are both over 3MB. Look for PNG compressors online to compress the image asset. 
- [] Compress your audio file if. Try reducing the length if possible.   

We've tested your effect out.
Screenshot (221)

**Comment by lopeselio** [comment]
@distroinfinity please take care of these changes before we merge. Bravo!

**Comment by distroinfinity** [comment]
@lopeselio sure on it!

**Comment by distroinfinity** [comment]
@lopeselio Hey I have optimized the pngs and audio file. Do give it a check. But I don't know for some reason the audio is still not rendering in the scene the effect is complete otherwise. If you could look into that and accept the PR if you feel its okay.

**Review by lopeselio — APPROVED** [review]
changes approved

**Comment by lopeselio** [comment]
@distroinfinity  I think you need to enable the audio patch to play in a loop. The effect is ready to be merged. All changes have been approved.

**Pull request merged**
